apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactcalculator  
  namespace: default      
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactcalculator
  template:
    metadata:
      labels:
        app: reactcalculator
    spec:
      containers:
      - name: reactcalculator
        image: your-docker-image:latest
        ports:
        - containerPort: 3000
