service:
  name: reactcalculator
  identifier: reactcalculator
  orgIdentifier: default
  projectIdentifier: Roy_D
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: reactcalculator-deployment
            type: KubernetesManifest
            spec:
              store:
                type: Git
                spec:
                  connectorRef: yourGitHubConnector
                  repoName: your-repo-name
                  branch: master
                  paths:
                    - path/to/your/deployment.yaml
                    - path/to/your/service.yaml
