service:
  name: reactcalculator
  identifier: reactcalculator
  orgIdentifier: default
  projectIdentifier: Roy_D
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: reactcalculator-deployment
            type: K8sManifest
            spec:
              store:
                type: Git
                spec:
                  connectorRef: RoyGitHub
                  repoName: reactcalculator
                  branch: master
                  paths:
                    - .harness/deployment.yaml
                    - .harness/service.yaml
