apiVersion: v1
kind: Service
metadata:
  name: reactcalculator-service  
  namespace: default             
spec:
  selector:
    app: reactcalculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer