pipeline:
  identifier: Build_reactcalculator_1728157929891
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: Roy_D
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: RoyGitHub
        repoName: reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_javascript_app
                  name: Build JavaScript App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
                      npm test
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: reactcalculator
          environment:
            environmentRef: reactcalculator
            deployToAll: false
            infrastructureDefinitions:
              - identifier: royinfrastructure
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    manifests:
                      - manifest:
                          identifier: reactcalculator-deployment
                          type: K8sManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: RoyGitHub
                                repoName: reactcalculator
                                branch: master
                                paths:
                                  - .harness/deployment.yaml
                                  - .harness/service.yaml
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
